// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package rds

type Album struct {
	Title string
}

type Artist struct {
	Name string
}

type Recording struct {
	Path       string
	Song       string
	Artist     string
	Album      string
	Cddb       *string
	Constraint interface{}
}

type Song struct {
	Title string
}
